clear all;clc;
imageFileNames = {'E:\Often\practice\monocular\checkerboard_cab\orig\1\1 (1).BMP',...
                  'E:\Often\practice\monocular\checkerboard_cab\orig\1\1 (2).BMP',...
                  };
imshow(imageFileNames{1});